
env = Environment(CC = 'g++', CCFLAGS = ['-Wall', '-O3'])

env.Object('main.cpp')
env.Program(target = 'main', src = ['main.o'], LIBS = ['primesieve', 'miller-rabin-det'], LIBPATH = ['../../../Libs/Miller_Rabin_Deterministic'])

